### ISSUE TITLE
Internal server error and disconnect from server

### ISSUE THREAD

**Issue by helkarakse** [Beyond-Reality/Beyond-Reality-Divergence#128]
Server side error: http://pastebin.com/vjbSqBeb

Caused by right clicking a vanilla torch on the compacter.

**Comment by helkarakse** [comment]
Seems like this also happens on a few other modded blocks, tinker's construct high oven duct for one.

**Comment by Githubaccountlol** [comment]
Happens with a lot of the tinkers' objects, not around to verify specifics right now but faucet/basin combos do it (can't remember if it's one or both), and I had trouble actually placing torches onto my smeltery and getting them to stick serverside.  Didn't think much of it at the time but it's likely the same behavior, difference being when it happens inside a mod object/gui the rejection is more violent.  When it happens placing torches in the world you just end up out of sync and nothing bad happens.

I would first suspect something is modifying the behavior of torch placement, rather than the mods being interacted with.  Might want to hold off spreading reports around until the common denominator is identified.

**Comment by helkarakse** [comment]
I think it's the enviromine torch handler, as they seem to share the common root problem.

**Comment by bdew** [comment]
Bug in enviromine - https://github.com/EnviroMine/EnviroMine-1.7/issues/165

I've added a workaround to BDLib that will prevent crashes in most cases in my mods.

**Comment by Dominance** [comment]
Thanks bdew!

**Comment by Dominance** [comment]
Fixed next Version thanks again bdew!
