### ISSUE TITLE
update 1.09

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#22]
after the update my sp game will not let me interact with anything outside the temple(cant break flowers, kill chickens or other mobs) its almost as if the lag was endless, the textures have also gone a bit funky
https://gyazo.com/76cbb541042fcb45afe9e11c2dbf2ca6 . hope this helps,have fixed some of the probs with a re-install but still can't place the furnace.

**Comment by Dominance** [comment]
The furnace may be a issue! When you add items to progression the default one is a furnace as a place holder until it is changed. I must of just overlooked one as I added about 400 items to the system in this update. as far as the textures go It may be due to me including a mod that pre sets your options for you. Turns all the graphics and what not down by default.

**Comment by Dominance** [comment]
Fixed it for 1.0.9 you will have to just reinstall. Due not that any progression made will be reset. It is important for legit testing to keep the keys so you can just go back and reunlock what you have already learned.

**Comment by Dominance** [comment]
I cannot replicate the graphic errors. It may be you having minecrafts shaders enabled on accident ?
