### ISSUE TITLE
1.2.8 Milestone Make suggestions here please!

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/Beyond-Reality-Divergence#251]
- Fix temple oddity's such as Renaming tutorial area to Hall Of legends and adding http://i.imgur.com/PjAytiv.png back into it. 
- Finish transferring / completing In game documentation 
- ~~Finish the quest books lore and gate location corresponding text~~ (Done Thanks B0b!)
- Completely add/remove in any new mods if any to ether tech / magic / combined (Not sure if there will be any) Finalize the mod list
- Add in cut scene using https://github.com/GenDeathrow/CutScenes-1.7.10/wiki that explains the first steps to the pack and lore. // Lock HQM behind progression add a chair/new model to Hall of legends (Tutorial area) that unlocks the books usage.
- Replace chair with new model (It was just a placeholder kinda joke I tossed together.)
- Balance AgriCraft (Implement https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/247)
- Fix Forestry Bio-Mass issues or update to forestry 4 
- ~~Remove Rot from milk / Add recipe for spoiled milk (Added to drying rack)~~ _Done_
- Redo rune of summer recipe to use Glimmering melon. Revert melon slices back to 7 days rot.
- ~~Add loot to adventure backpack and water bottles.~~ _Done_
- Add Thermal Smeltery, Project Blue, Survival tweaks and possible Arcane engineering as a combo mod.
- Redo Tech tree to allow for more choices or paths.
- More to come

**Comment by mrbaggins** [comment]
I'd go with Forestry 4, as that apparently solves a bunch of stuff, including a bunch of performance improvements, but it will mean another world reset (all old forestry trees / leaves / woods will break, if I recall). At this point though, pretty sure I'd be MCediting my village to a new world regardless.

**Comment by foopex** [comment]
Add common expedition items to adventure backpack and enable recipe.

Adding water bottles to it would be a nice start.

Could be considered an alternative to stacking water bottles.

**Comment by Crumbology** [comment]
Could we have an alternative recipe for rune of summer using glistering melons, costs gold to make to prevent them from rotting this way, and are no longer food, but should help with rune automation if you are willing to pay the extra.

Rotting milk, is this really necessary?  It just seems to mess up some autocrafting, I realise it makes sense in the overall rotting scheme of things, but it's really not a food.

**Comment by Eliteneet** [comment]
Give dirt gravity, so that it behaves like sand and gravel. Floating blocks of dirt make no sense and its used too often as an easy and safe building block. Atleast in my experience.

**Comment by Dominance** [comment]
I at one time had dirt with gravity. Its only disabled due to performance issues. That and it used to crash with rock dust.

**Comment by Eliteneet** [comment]
Ah I see, thats too bad.

**Comment by b0bst3r** [comment]
We had a discussion over the tech tree and how static it was and giving you little choice, we came up with alternatives for you to look at and either dismiss or take on.

Mine - http://postimg.org/image/ajd95uy15/ whilst still needing 90% of the mods towards the end it gives you more initial choice as to where you want to go.

Crumbology's - http://postimg.org/image/l4x4hv4cp/ this is a totally different approach which would require the quests reworking with rep to unlock the next tier of mods

**Comment by Leftorius** [comment]
-instead of binnie mods -> Gendustry? (because of forestry 4.1 etc.)
-http://minecraft.curseforge.com/projects/survival-tweaks Player Collision is just ! 
-Galacticraft as the last tech step? I would really like to explore some planets in the end! and then the ores on those planets are more (Moon has just Iron and Redstone or something like that, or huge deposits) so you WANT to go there and explore :D

**Comment by Dominance** [comment]
As for binnies I hope I do not have to go that path again. I will only if 100% necessary. As making a line of bees with gendustry is a daunting task. Survival tweaks looks great, If some of the nether features can be disabled it would fit well. As for Galacticraft not going to happen. I do not wish to replicate a exact feature that is in Beyond Reality already.

**Comment by mrbaggins** [comment]
> As for binnies I hope I do not have to go that path again. I will only if 100% necessary. As making a line of bees with gendustry is a daunting task

I can't work out if that means you like binnies, like gendustry, dislike binnies or dislike gendusty :P

**Comment by Leftorius** [comment]
as for binnies mods, I don't know if we're lucky he will update it, if we're unlucky it could take a while but forestry 4.x is a huge update to exist worlds so, at some point it wouldn't make sense to wait longer. For now we can wait, but with gendustry you could make custom hives too in the newer version.

Survival tweaks is fully configurable.

With Galacticraft okay, I can understand that and in the end, we have a lot to do already. 

Another mod I found: http://minecraft.curseforge.com/projects/arcane-engineering don't know how it would fit in Divergence.

http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/ for ProjectRed?

I know we're on ATLauncher but this is the only thing I really think FTB has done well: http://minecraft.curseforge.com/projects/ftb-utilities 

This maybe for the future so we can combine endgame Metals (Draconium?) with Tcon?
http://minecraft.curseforge.com/projects/contenttweaker

http://minecraft.curseforge.com/projects/router-reborn because router :D 

That's all I have in mind, but what I really want to see are some more or dangerous mobs but I'm really happy with the pack how it is right now. :) Good work and thanks for your time and efforts!

**Comment by Dominance** [comment]
As for binnies / gendustry I love them both. BR has gendustry and is the only pack that has a full fledge custom bee lines using it. I wanted divergence to be different than BR hence why I went with binnies. At the time when first added he was updating like a mad man and now he is back to school most likley and is MIA. I dont want to use gendustry if at all possible.
Not really sure why I have yet to add project blue. Its def going in. As for FTB Utilities I think lav did a great job making the mod. How ever in my view Its for there packs and makes there pack unique. I think Content tweaker could possible be used for something just not with draconium. Routers reborn = no Arcane Engineering = yes Keep em coming!

**Comment by Crumbology** [comment]
http://www.curse.com/mc-mods/minecraft/227661-thermal-smeltery

Offers the ability to melt metals in the magma crucible, would be nice to be able to totally replace the smeltery once Thermal Expansion is unlocked.

**Comment by Crumbology** [comment]
How about a mid tier of Botania, remove Terrasteel from the Elven Portal ingredients and have an Elven Tier allowing the use of anything not involving Terrasteel.  This would allow for faster spreaders, some more interesting lenses and a few more mid game items that seem locked really late, like the drum of the gathering and the Elementium tools and armors which will probably be ignored totally with the current setup.

Was thinking this could sit alongside Blood Magic and Chromaticraft area, with the same costs.

**Comment by b0bst3r** [comment]
Following on from Crumbs comment about thermal smeltery how about adding then metals to the Rotarycraft Rock Melter?

**Comment by Dominance** [comment]
Rex: 

I was wondering if for the next patch we could split AE into a basic and advanced version like some of the other mods.

Basic would not allow you to place a controller so you would be limited in channels. This would greatly help with storage in that lots of items don't seem to stack and storage is a serious pain atm. Even using Storage Drawers and modular it is still a pain.

It would also give a taste but also give something more to aim for.

**Comment by Crumbology** [comment]
http://www.curse.com/mc-mods/minecraft/237271-gadomancy

Potential replacement for Shamanry or Thaumic Upholstery, just came out of beta, adds a coupla golem cores, a way to auto activate the runic altar and some other useful things that don't seem game breaking.

**Comment by mrbaggins** [comment]
Showerthought: Is there a reason we need the temple? Is it just a lore thing? Because the book could totally give you an item (the chair, or whatever is replacing it) that you could place in your own trophy room and sit in yourself. Saves a lot of problems, avoids having to manage it being spawned in....

I realise it's probably a design choice to have it, but yeah, showerthought.

**Comment by Leftorius** [comment]
http://minecraft.curseforge.com/projects/neat

**Comment by BoxcarPenguin** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442761-wip-small-boats-elegant-punt-whitehall

This mod would make ocean transportation much nicer.

**Comment by Leftorius** [comment]
so any news on the next update? :I

**Comment by choum33** [comment]
Hello,

As we can carry less it's normal that we use wagons and trains. It would be great to include traincraft mod to your amazing modpack with a dependency to railcraft or another one to have more locomotives and improved tracks ;) Or unlobk this mod part by part in another researchs ;)

My best regards

**Comment by sophieneuenmuller** [comment]
I would like to ask if it would be possible to add a harder ores flower for mana infused ingots. One of the things I've noticed is that going down the magical route is somewhat harder, due to using the flowers on the surface to go for the ores I want, specially since strip mining is highly discouraged. However I am struggling so much to find enough of it to do even the basics of botania. In fact I decided to forget that magic exists until I get the autominer in IE. If that is intended, completely ignore it.

Another suggestion would be to add images of how the dungeons entrance look from the outside to Divergence book. It is getting tedious trying to find the nether key even with the help of JourneyMap to have a look from the skies. Found a few dungeons already, including one with a "boss" but not that dungeon yet. Having the images of what to search would be useful.

As for the tech tree redistribution, I would go with b0bst3r one, feels more that you have a choice and, when choosing, you have to think forward about what you will have available to unlock. Should I go down the bee path for rarer resources or go with IE for the usual ores? Early jetpack or wait for a modular armor? That kind of choices. If you integrate a bit more the mods on each line would make that tree better, for example using Pneumaticacraft plastics or Forestry tubes in recipes further down the line but, not necessary.

**Comment by mrbaggins** [comment]
Search in magical biomes for magical ore. You get way more in magical forests, but even just exploring random ravines I find more than enough to use.

I think there's 3 types of dungeon, and they're all pretty obvious. A big flat rectangle with a little glowstone roofed pegola is the easy one. A big double store celtic barn thing with arcane lamps is one, and the big brown pyramid with ender pools is last. All three are SUPER obvious on the map as being odd/interesting.

I'm not a fan of traincraft. doesn't fit the game style and doesn't really add anything particularly useful.

**Comment by sophieneuenmuller** [comment]
Then I've been unlucky with the dungeon, time to keep searching. Though it could be that dungeon would be more hidden, since it will unlock the nether after all. About magic ore, is that noted anywhere? I may have missed that info. EDIT: Found the temple. As I asked for the temple it appears. And the boss once engaged it will shoot you through walls completely ignoring them. Great.

**Comment by mrbaggins** [comment]
There's at least 3 different "bosses" if it's the giant guy that hulk smashes the floor, yeah, he sucks.

But you get his cool hammer if you kill him, letting you do it.

**Comment by choum33** [comment]
100% agree to change tech tree path, Mostly don't understand why extra bees is needed to unlock logistic pipes for exemple ;)
Make the pack harder with stronger monsters (zombie awarness or something) to motivate players to play toguether. Maybe lower the ores generation too.
About the tech, maybe change the advanced researchs to not to have to craft basic ones and then use them to craft the upgraded ones, replace this with a dedicated thing to craft. Please increase the RFs and mana needed to craft the researchs ;) 
We like challenge ;) 

Anyway thanks for your great job ;)

**Comment by choum33** [comment]
Hello Mrbaggins,

I just wonder if it possible to have a fixupdate 1.2.7.2 tu upgrade some mods? Many of them fixed bugs like immersive engineering and some others ;)

My best regards

**Comment by mrbaggins** [comment]
Oh I'm not in charge, that's Dominance. I was just putting in a counter opinion in the name of discussion.

**Comment by Bewilderer** [comment]
Maybe the progression could be edited so that you would gain access to the mod when you unlock it, instead of having to travel to the temple and hunting down the chair

**Comment by Dominance** [comment]
Changing the tech tree would take a huge amount of time, Some of these features listed I will attempt to implement. Most likley most on the list will wait until Divergence 2.0 or what ever for a newer minecraft version such as 1.9.4 / 1.10

I have learned a lot and know what I would do differently from the start to make divergence a better pack. Somethings is best left to a fresh start.
