### ISSUE TITLE
Infinite water from MagnetiCraft turned into ice

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#263]
I guess it's some kind of misguided season effect, but an Infinite Water block from MagnetiCraft turned into ice (along with "normal" water near it). The block is similar to an aqueous accumulator.

**Comment by b0bst3r** [comment]
This is fixed in the updated (0.6.0-beta1) Magneticraft, the Infinite water block was given properties of a water block which is why it gets replaced when you put a block next to it (clicking the side of the block).

https://github.com/cout970/Magneticraft-API-and-Issues/issues/34

But refineries are broken in 0.6.0-beta1 so probably need to wait for the version after.

**Comment by Belgabor** [comment]
Ah I see, well I decided to turn off seasons anyways, so it won't affect me any more. Harder wildlife seems to break vanilla water freezing rules, not going to risk explosions because of that...

**Comment by Buuz135** [comment]
Fixed
