### ISSUE TITLE
Oversights(?)

### ISSUE THREAD

**Issue by Alzarath** [Beyond-Reality/Beyond-Reality-Divergence#266]
## Ore Generation

Beyond Reality doesn't seem to affect all ores. From what I've observed so far, it seems to be the case for Redstone and Coal ore. The amount it generates doesn't seem unreasonable, though. What doesn't seem okay is Apatite. I'm not sure what its uses are, but I noticed the ore blocks spawn in massive clumps and not the sparse ores.
## Tools

I see the intention seems to be to focus solely on Tinkers' Construct for tools. But there also seem to be exceptions. Swords are largely unaffected. More specifically:
### Botania

Manasteel tools are disabled. The Vitreous Pickaxe is enabled. Elementum and Terrasteel Tools are enabled.
### Thaumcraft

All tools are enabled. Thaumium tools are common in chests, so if you happen to be near a pyramid at the start, you're able to skip a large part of the progression.
## Quests

Many of the quest rewards overlap with their respective opened quest gate chest contents. For example, when getting the Tinkers' Construct reward, you also open the gate that has a chest with many of the required Tinkers' Construct items. You end up with two Smeltery Controllers, which isn't particularly useful.

**Comment by Dominance** [comment]
Ore generation is correct. Just because it does not have a special block does not mean it was a oversight. 

Don't know where you are getting the solely focusing on tinkers part. as hammers are disabled from the get go. For your normal 1 block at a time. Yes Its needed almost to progress at a decent pace. 
As for botania you may want to look at what is required to gain elementum / terrasteel. You wont be there for a long while. The basic tool progression is not a huge concern of mine. 

The rewards where added for servers as its needed. Most run off with the starting chest loot. After the tutorial you will notice there is no rewards given at all what so ever, as this is really not a HQM pack.

**Comment by Alzarath** [comment]
That is why I added (?) to it.

Obviously I got it from the fact that vanilla tools are disabled. My concern was more toward the Vitreous Pickaxe, which seems comparable to a normal pickaxe in the first place. I chalked that up to its utility in glass-retrieval. My main concern was the Thaumcraft loot generation. But if you think it's fine how it is, so be it.

I understand the rewards from the quest book, but the similar temple rewards seem superfluous. On a related note, the research chairs don't exactly fit well in the temple. It looks like they're meant to be in a 3 tall location while being cramped in a two tall, and when you sit in it all you see is blackness most likely due to your vision being in the ceiling.
