### ISSUE TITLE
ChromaticCraft Crystals Cause PermaCrash

### ISSUE THREAD

**Issue by BoxcarPenguin** [Beyond-Reality/Beyond-Reality-Divergence#272]
I had a player try to place a ChromaticCraft crystal. It tried to emulate the behavior of ingots (becoming an entity). This caused a permanent crash near the temple, so no new players could connect without instantly crashing. I fixed this issue in MCEdit, but the danger of players doing it again is high,

[crash-2015-12-01_15.08.10-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/49042/crash-2015-12-01_15.08.10-client.txt)

**Comment by Belgabor** [comment]
Odd, we did that quite a lot and didn't have this issue. I did pull stacks on stacks from my server anyways, I couldn't place AutoMagy recrystal...

**Comment by BoxcarPenguin** [comment]
That's interesting. Maybe the crash report will speak for itself. According to the player who caused the crash, he "tried to eat a red crystal" and we had to revert to a backup. Perhaps the crash is related to temple blocks?

**Comment by Pyriana** [comment]
I had the same issue with a black crystal (I accidently right clicked on the runed little caves with 3 chests and then 3 more chests) every time I logged in it would try to load that entity and crash, my friend teleported me out of it during one of my login attempts and I went and sealed that cave off (since it's just 3 of us playing on that server it's not a big deal to remove it)

**Comment by Dominance** [comment]
Should be fixed in 1.2.8
