### ISSUE TITLE
No recipe for BC Factory Refinery

### ISSUE THREAD

**Issue by LordPinkerton** [Beyond-Reality/Beyond-Reality-Divergence#328]
Don't know if this is intentional, but there does not seem to be a way to build a Refinery for BC.

**Comment by Dominance** [comment]
It's intentional need to use build craft additions version.
Don't know if this is intentional, but there does not seem to be a way to build a Refinery for BC.

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/328

**Comment by LordPinkerton** [comment]
Thank you for the clarification.
