### ISSUE TITLE
OpenModularTurrets Tier 2 Locked behind Thermal Expansion

### ISSUE THREAD

**Issue by LordPinkerton** [Beyond-Reality/Beyond-Reality-Divergence#329]
I was curious if this was intended, but the tier 2 and above bases for the Open Turrets, which is unlocked in the Basic quests, is set to require stuff from Thermal Expansion, which if I'm not mistaken, is end-game Tech quest stuff. In the config file for Open Turrets, the recipe switching is set to =auto, which I imagine detects what mods are installed and defaults to one, this case being Thermal Expansion. Again, was this intended, or does this variable need to be set to =vanilla, which only requires stuffs from the Open Turrets mod to create those items?

**Comment by Dominance** [comment]
Without it the recipes are a tad bit to easy. This has came up before and I thought I had fixed it once or maybe I didn't. Ether way it does need to be.

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/329
