### ISSUE TITLE
Unable to open Thaumcraft Treasure bags.

### ISSUE THREAD

**Issue by LordPinkerton** [Beyond-Reality/Beyond-Reality-Divergence#330]
Even with enough inventory space, I do not seem to be able to open these treasure backs from the Thaumcraft mod. Don't know if this is intended to limit gained resources or not.

**Comment by Dominance** [comment]
It's intended only left in as there is no easy way to disable and for trading.
Even with enough inventory space, I do not seem to be able to open these treasure backs from the Thaumcraft mod. Don't know if this is intended to limit gained resources or not.

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/330
