### ISSUE TITLE
Intense lag when near a dungeon

### ISSUE THREAD

**Issue by calac64** [Beyond-Reality/Beyond-Reality-Divergence#334]
So far the game has not crashed, and the AT Launcher Log does not show anything out of the ordinary. But every time I approach this dungeon, I get immense lag. I actually had to delete a world after entering one. (The FPS hit 0 and the server was ~ 400,000ms behind continuously. It took about a half hour to move to a new chunk).

I can post a picture, but the dungeon looked kinda like a desert well from vanilla minecraft, except pointed at the top with a glow stone cap.

**Comment by Dominance** [comment]
Hum yes I know the one, Cannot replicate this issue. Have you had it happen since?

**Comment by calac64** [comment]
No, I have not been able to replicate it since deleting that save. However, upon entering a similar dungeon in a different save file, I discovered that there were no Mobs present (On hard difficulty).

**Comment by Dominance** [comment]
Sometimes they all die off if you don't immediately enter.
On Jun 28, 2016 11:28 PM, calac64 notifications@github.com wrote:No, I have not been able to replicate it since deleting that save. However, upon entering a similar dungeon in a different save file, I discovered that there were no Mobs present (On hard difficulty).
