### ISSUE TITLE
Where to find Aluminum?

### ISSUE THREAD

**Issue by obuw** [Beyond-Reality/Beyond-Reality-Divergence#353]
I just started playing this modpack (latest version on AT Launcher - 1.3.1.1-Beta). The Divergence book does not mention Aluminium ore, and I am having great trouble finding it. I have been playing for 3 days now. 

Found a mineshaft, tons of  ore chunks (including 6 diamond ore chunks and 20 platinum ore chunks) but only a single aluminum ore chunk. 

Flown around in creative mode, checking for plants, and I can't find any of the plants that supposedly spawn above aluminum ore (according to the wiki). 

Found some massive surface rock biomes, got tons of tin ore chunks (100+), an iron vein, a limonite vein, but zero aluminum.

Found a temple, defeated the guardians, the end chest contains lots of copper, tin, iron, gold but no aluminum.

I would have thought worldgen is bugged, if it wasn't for that single piece of aluminum ore chunk I found in the mineshaft.

Searching around for answers, I see people talking about not being able to find aluminum, and people giving advice about searching under streams, but I assume that is for the older versions of the pack that use ATG? I have been searching near rivers but found zero ores around those as well.

So where does it spawn? Is it really meant to be this rare? Am I meant to use my precious gold ingots to make tinker casts instead?

**Comment by obuw** [comment]
Nevermind, I just found a swampland biome, then found flowers and then a huge surface deposit in hardened clay!

**Comment by Dominance** [comment]
Aluminum aka bauxite ore. Spawn's most commonly in Mesa biomes or yeah
under Rivers. It's normally only two to three blocks below the surface and
sometimes the additional red clay it generates can be seen without digging
at all in a river.

**Comment by Dominance** [comment]
It can be a headache sometimes. I once searched for five hours for
diamonds. After finding and mining headed back to then find them ten blocks
away from my underground base

On Apr 19, 2017 7:51 AM, "obuw" <notifications@github.com> wrote:

Nevermind, I just found a swampland biome, then found flowers and then a
huge surface deposit in hardened clay!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/353#issuecomment-295232758>,
or mute the thread
