### ISSUE TITLE
Pulverising Raw Ores (harder ore Raw Ores)

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#90]
Pulverise 1 Raw Gold Ore and you get 3 tiny gold dust (working correctly)
Pulverise 1 Raw Iron Ore and you get 3 tiny iron dust (working correctly)
Pulverise 1 Raw Tin Ore and you get 1 Big Tin Dust and a % chance at 3 tiny iron dust (broken)
Pulverise 1 Raw Copper Ore and you get 1 Big Copper Dust and a % chance at 3 tiny gold dust (broken)
Pulverise 1 Raw Lead Ore and you get 1 Big Lead Dust and a % chance at 3 tiny silver dust (broken)
Pulverise 1 Raw Silver Ore and you get 1 Big Silver Dust and a % chance at 3 tiny lead dust (broken)

You cannot pulverise Raw Uranium, limonite or Aluminum Ores from Harder Ores.

By Pulverise I mean placing the Raw Ore in a Thermal Expansion pulverisor.
By Big Dust I mean a single dust which smelts straight into an ingot.

By Working correctly I presume this recipe is correct
By broken I presume this recipe is well and truly broken :)

@draco18s is this on your side?

**Comment by Draco18s** [comment]
This is likely on my end. I'll take a gander in the next day or two.

**Comment by Draco18s** [comment]
Located offending code.
Was my mistake in the oredict requests.  I've updated the broken recipes to use the correct items.  Fixed for next version.

I cannot locate the details on the complete recipe for either uranium or aluminum, i.e. their secondary result items and chances.  So at this time I am unable to implement those recipes.  There may also be primary result items I am unaware of.

Limonite is not crushable: you need to smelt the water out of it and turn it into an iron chunk first, this is intentional (limonite is early-access iron, but crap once you've got decent automation and an iron vein).

**Comment by Dominance** [comment]
I don't believe with thermal expansion there is a secondary chance item for ether Uranium or Aluminum when you pulverize them.

**Comment by Draco18s** [comment]
Noted.  How should I handle the platinum?

**Comment by Dominance** [comment]
Platinum is also something iirc that does not have a secondary as well. If anything Iron is about as realistic as it gets for secondary's on some of these things.

**Comment by Draco18s** [comment]
No no, it IS a secondary result from nickel.  The question is whether or not there's a tiny dust pile for it already.

**Comment by b0bst3r** [comment]
Not in the pack there isn't

**Comment by Dominance** [comment]
Fixed in upcoming release.
