### ISSUE TITLE
NEI display errors with the Millstone and Harder Ores

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#91]
Within NEI the following happens:

Pressing U on Raw Gold Ore shows the millstone recipe for the quantity of Raw Gold Ore you are holding instead of 1 Raw Gold Ore > 2 Tiny Gold Dust.  For example if you are hold 63 Raw Gold Ore and press U on it the millstone recipe shows 63 Raw Gold Ore to make 2 Tiny Gold Dust.

The same applies to Raw Iron Ore.

Pressing U on Raw Tin, Silver, Lead, copper and aluminum shows the millstone recipe as 9 Raw Ore > 2 tiny dust.

Just a note that all the recipes work correctly (1 Raw to 2 tiny) the above are just NEI display errors.

**Comment by Dominance** [comment]
Umm hmmm not sure if that is something on my end of the fixing spectrum or not.

**Comment by Dominance** [comment]
I hate to keep poking @draco18s But I have not found anything on my end to cause this visual glitch.

**Comment by Draco18s** [comment]
I'm not _quite_ seeing the described behavior, but I am seeing something close.

**Comment by Draco18s** [comment]
And fixed for next version.

**Comment by b0bst3r** [comment]
Yay  :D any idea when that might be release Draco?

**Comment by Draco18s** [comment]
I was just writing up a PM to the Agricraft developer for a long-term integration plan and I'd really like to get the foundations needed for that into the next update so that the changes to HardLib are already made (next update includes a lib change, which means it _must_ increment the first two version numbers).  If I hear back quickly, then I could make those changes today.

If I don't hear back by tomorrow, then I'll just push what I have then.

**Comment by Draco18s** [comment]
New version pushed.

**Comment by Dominance** [comment]
Thanks again!
